/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IMS;
import static IMS.stockManagement.itemList;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.TimeZone;
import javax.swing.Timer;
import java.io.BufferedWriter;
import java.io.*;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.ZoneId;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Ryan
 */
public class POSOrder extends javax.swing.JFrame {
    public int UID;
    int overallprice = 0;
    int ordernumber = 0;
    DefaultTableModel cartlist;
    DefaultTableModel model;
    stockManagement stock = new stockManagement();
    
    
    static char[] getlogFilename() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private Timer timer;
    private final TimeZone philippineTimeZone;
    private String fullName;

    /**
     * Creates new form POSOrder
     */
    public POSOrder() {
        initComponents();
        philippineTimeZone = TimeZone.getTimeZone("Asia/Manila");
        loadDateTime();
        startTimer();
        cartlist = (DefaultTableModel)customercart.getModel();
        model = (DefaultTableModel)orderlist.getModel();
    }
    public void setFullName(String fullName) {
        fullNameLabel.setText(fullName);
        
    }
    
    

    public final void loadDateTime() {
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("MMMM dd, yyyy");
        SimpleDateFormat sdf2 = new SimpleDateFormat("hh:mm:ss a");
        sdf.setTimeZone(philippineTimeZone);
        sdf2.setTimeZone(philippineTimeZone);
        timeLabel.setText(sdf2.format(date));
        dateLabel.setText(sdf.format(date));
    }

    private void startTimer() {
        timer = new Timer(1000, (evt) -> updateTimeLabel());
        timer.start();
    }

    private void updateTimeLabel() {
        Date time = new Date();
        SimpleDateFormat sdf2 = new SimpleDateFormat("hh:mm:ss a");
        sdf2.setTimeZone(philippineTimeZone);
        timeLabel.setText(sdf2.format(time));
    }
    
    public String getLogoutTime() {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")
            .withLocale(Locale.ENGLISH)
            .withZone(ZoneId.of("Asia/Manila"));
        LocalDateTime now = LocalDateTime.now(ZoneId.of("Asia/Manila"));
        String logoutTime = now.format(formatter);
        return logoutTime;
    } 
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        fullNameLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        schwarzbier = new javax.swing.JButton();
        bourbonwhisky = new javax.swing.JButton();
        fruitvodka = new javax.swing.JButton();
        plainvodka = new javax.swing.JButton();
        plymouthgin = new javax.swing.JButton();
        chardonnaywine = new javax.swing.JButton();
        cabernetsauvignonwine = new javax.swing.JButton();
        oldtomgin = new javax.swing.JButton();
        distilledsoju = new javax.swing.JButton();
        navyrum = new javax.swing.JButton();
        sweetcider = new javax.swing.JButton();
        stoutbeer = new javax.swing.JButton();
        scotchwhisky = new javax.swing.JButton();
        bittercider = new javax.swing.JButton();
        rhumagricole = new javax.swing.JButton();
        productprice = new javax.swing.JTextField();
        productname = new javax.swing.JTextField();
        productquantity = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        totalprice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        calculateTotal = new javax.swing.JToggleButton();
        addtoCart = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        customercart = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        overallcost = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        orderaddress = new javax.swing.JTextField();
        comfirmcart = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        seethefile = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        orderlist = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        enteredaddress = new javax.swing.JTextField();
        processOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Return Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Get Membership");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Report Logs");

        jButton5.setBackground(new java.awt.Color(102, 102, 102));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Get Total");

        logoutButton.setBackground(new java.awt.Color(102, 102, 102));
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Log out");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(15, 15, 15)))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setLayout(null);

        fullNameLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        fullNameLabel.setForeground(new java.awt.Color(51, 51, 51));
        fullNameLabel.setText("jLabel2");
        jPanel5.add(fullNameLabel);
        fullNameLabel.setBounds(140, 0, 130, 40);

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Employee Name:");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(20, -10, 130, 60);

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Time:");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(280, 0, 37, 40);

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText(" Date: ");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(420, 0, 44, 40);

        timeLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        timeLabel.setForeground(new java.awt.Color(51, 51, 51));
        timeLabel.setText("jLabel1");
        jPanel5.add(timeLabel);
        timeLabel.setBounds(320, 0, 100, 40);

        dateLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(51, 51, 51));
        dateLabel.setText("jLabel3");
        jPanel5.add(dateLabel);
        dateLabel.setBounds(460, 0, 100, 40);

        jPanel6.setLayout(null);
        jPanel6.add(jSeparator1);
        jSeparator1.setBounds(0, 50, 0, 3);

        jPanel7.setBackground(new java.awt.Color(102, 102, 102));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("TOTAL AMOUNT");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel9)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel7);
        jPanel7.setBounds(390, 10, 170, 101);

        jPanel8.setBackground(new java.awt.Color(102, 102, 102));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("SUB TOTAL:");

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("DISCOUNT:");

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("TAX:");

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("TOTAL ITEMS:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13))
                .addGap(186, 186, 186))
        );

        jPanel6.add(jPanel8);
        jPanel8.setBounds(10, 10, 370, 100);

        schwarzbier.setText("Schwarzbier");
        schwarzbier.setPreferredSize(new java.awt.Dimension(120, 50));
        schwarzbier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schwarzbierActionPerformed(evt);
            }
        });

        bourbonwhisky.setText("Bourbon Whisky");
        bourbonwhisky.setPreferredSize(new java.awt.Dimension(120, 50));
        bourbonwhisky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bourbonwhiskyActionPerformed(evt);
            }
        });

        fruitvodka.setText("Fruit Vodka");
        fruitvodka.setPreferredSize(new java.awt.Dimension(120, 50));
        fruitvodka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fruitvodkaActionPerformed(evt);
            }
        });

        plainvodka.setText("Plain Vodka");
        plainvodka.setPreferredSize(new java.awt.Dimension(120, 50));
        plainvodka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plainvodkaActionPerformed(evt);
            }
        });

        plymouthgin.setText("Plymouth Gin");
        plymouthgin.setPreferredSize(new java.awt.Dimension(120, 50));
        plymouthgin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plymouthginActionPerformed(evt);
            }
        });

        chardonnaywine.setText("Chardonnay Wine");
        chardonnaywine.setPreferredSize(new java.awt.Dimension(120, 50));
        chardonnaywine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chardonnaywineActionPerformed(evt);
            }
        });

        cabernetsauvignonwine.setText("Cabernet Sauvignon Wine");
        cabernetsauvignonwine.setPreferredSize(new java.awt.Dimension(120, 50));
        cabernetsauvignonwine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cabernetsauvignonwineActionPerformed(evt);
            }
        });

        oldtomgin.setText("Old Tom Gin");
        oldtomgin.setPreferredSize(new java.awt.Dimension(120, 50));
        oldtomgin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldtomginActionPerformed(evt);
            }
        });

        distilledsoju.setText("Distilled Soju");
        distilledsoju.setPreferredSize(new java.awt.Dimension(120, 50));
        distilledsoju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distilledsojuActionPerformed(evt);
            }
        });

        navyrum.setText("Navy Rum");
        navyrum.setPreferredSize(new java.awt.Dimension(120, 50));
        navyrum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navyrumActionPerformed(evt);
            }
        });

        sweetcider.setText("Sweet Cider");
        sweetcider.setPreferredSize(new java.awt.Dimension(120, 50));
        sweetcider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sweetciderActionPerformed(evt);
            }
        });

        stoutbeer.setText("Stout Beer");
        stoutbeer.setPreferredSize(new java.awt.Dimension(120, 50));
        stoutbeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stoutbeerActionPerformed(evt);
            }
        });

        scotchwhisky.setText("Scotch Whisky");
        scotchwhisky.setPreferredSize(new java.awt.Dimension(120, 50));
        scotchwhisky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scotchwhiskyActionPerformed(evt);
            }
        });

        bittercider.setText("Bitter Cider");
        bittercider.setPreferredSize(new java.awt.Dimension(120, 50));
        bittercider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bitterciderActionPerformed(evt);
            }
        });

        rhumagricole.setText("Rhum Agricole");
        rhumagricole.setPreferredSize(new java.awt.Dimension(120, 50));
        rhumagricole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rhumagricoleActionPerformed(evt);
            }
        });

        productprice.setEditable(false);

        productname.setEditable(false);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Order No.");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Quantity");

        totalprice.setEditable(false);
        totalprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalpriceActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Price");

        calculateTotal.setText("Calculate Total");
        calculateTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateTotalActionPerformed(evt);
            }
        });

        addtoCart.setText("Add to Cart");
        addtoCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtoCartActionPerformed(evt);
            }
        });

        customercart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Quantity", "Price", "Total Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        customercart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customercartMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(customercart);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LiquorPics/FantasticFourLogo.png"))); // NOI18N

        overallcost.setEditable(false);
        overallcost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overallcostActionPerformed(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Total Price");

        orderaddress.setEditable(false);
        orderaddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        orderaddress.setPreferredSize(new java.awt.Dimension(72, 25));

        comfirmcart.setText("Add Order");
        comfirmcart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comfirmcartActionPerformed(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Total Cost");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(817, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(393, 393, 393))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(schwarzbier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(20, 20, 20)
                                    .addComponent(plainvodka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(20, 20, 20)
                                    .addComponent(fruitvodka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(chardonnaywine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(20, 20, 20)
                                    .addComponent(plymouthgin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(navyrum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(20, 20, 20)
                                    .addComponent(sweetcider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(20, 20, 20)
                                    .addComponent(stoutbeer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(scotchwhisky, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(20, 20, 20)
                                    .addComponent(bittercider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(rhumagricole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(20, 20, 20)
                                    .addComponent(distilledsoju, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(20, 20, 20)
                                    .addComponent(cabernetsauvignonwine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(bourbonwhisky, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(20, 20, 20)
                                    .addComponent(oldtomgin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(10, 10, 10)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(productname, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(productquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(productprice, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(totalprice, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(calculateTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(addtoCart))
                                    .addGap(30, 30, 30)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(400, 400, 400)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(overallcost, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(comfirmcart))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(400, 400, 400)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(orderaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(10, 10, 10)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(40, 40, 40)
                                    .addComponent(jLabel2))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(700, 700, 700)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(577, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(20, 76, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(schwarzbier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(plainvodka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fruitvodka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chardonnaywine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(plymouthgin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(10, 10, 10)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(navyrum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sweetcider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(stoutbeer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(scotchwhisky, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bittercider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(10, 10, 10)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rhumagricole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(distilledsoju, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cabernetsauvignonwine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bourbonwhisky, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(oldtomgin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(20, 20, 20)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(productname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(productquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(productprice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(totalprice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(calculateTotal)
                                    .addGap(7, 7, 7)
                                    .addComponent(addtoCart))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(8, 8, 8)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(overallcost, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comfirmcart, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(10, 10, 10)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(orderaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(70, 70, 70)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(0, 56, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("POS", jPanel2);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        seethefile.setText("Check Order");
        seethefile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seethefileActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Your Orders");

        orderlist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Quantity", "Price", "Total Price"
            }
        ));
        jScrollPane3.setViewportView(orderlist);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Enter the Order Number:");

        enteredaddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        enteredaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enteredaddressActionPerformed(evt);
            }
        });

        processOrder.setText("Process Order");
        processOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(processOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel16)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(seethefile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(enteredaddress)))))
                .addContainerGap(1006, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enteredaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(seethefile)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(processOrder)
                .addContainerGap(332, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Order List", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed

        String logoutTime = getLogoutTime(); // Call the method to get the logout time

        POSLogin POSLoginFrame = new POSLogin();
        POSLoginFrame.setVisible(true);
        POSLoginFrame.pack();
        POSLoginFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void schwarzbierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schwarzbierActionPerformed
        // TODO add your handling code here:
        productname.setText("Schwarzbier");
        productquantity.setText("1");
        productprice.setText("22");
    }//GEN-LAST:event_schwarzbierActionPerformed

    private void bourbonwhiskyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bourbonwhiskyActionPerformed
        // TODO add your handling code here:
        productname.setText("Bourbon Whisky");
        productquantity.setText("1");
        productprice.setText("28");
    }//GEN-LAST:event_bourbonwhiskyActionPerformed

    private void fruitvodkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fruitvodkaActionPerformed
        // TODO add your handling code here:
        productname.setText("Fruit Vodka");
        productquantity.setText("1");
        productprice.setText("24");
    }//GEN-LAST:event_fruitvodkaActionPerformed

    private void plainvodkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plainvodkaActionPerformed
        // TODO add your handling code here:
        productname.setText("Plain Vodka");
        productquantity.setText("1");
        productprice.setText("23");
    }//GEN-LAST:event_plainvodkaActionPerformed

    private void plymouthginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plymouthginActionPerformed
        // TODO add your handling code here:
        productname.setText("Plymouth Gin");
        productquantity.setText("1");
        productprice.setText("28");
    }//GEN-LAST:event_plymouthginActionPerformed

    private void chardonnaywineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chardonnaywineActionPerformed
        // TODO add your handling code here:
        productname.setText("Chardonnay Wine");
        productquantity.setText("1");
        productprice.setText("24");
    }//GEN-LAST:event_chardonnaywineActionPerformed

    private void cabernetsauvignonwineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cabernetsauvignonwineActionPerformed
        // TODO add your handling code here:
        productname.setText("Cabernet Sauvignon Wine");
        productquantity.setText("1");
        productprice.setText("26");
    }//GEN-LAST:event_cabernetsauvignonwineActionPerformed

    private void oldtomginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldtomginActionPerformed
        // TODO add your handling code here:
        productname.setText("Old Tom Gin");
        productquantity.setText("1");
        productprice.setText("32");
    }//GEN-LAST:event_oldtomginActionPerformed

    private void distilledsojuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distilledsojuActionPerformed
        // TODO add your handling code here:
        productname.setText("Distilled Soju");
        productquantity.setText("1");
        productprice.setText("24");
    }//GEN-LAST:event_distilledsojuActionPerformed

    private void navyrumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navyrumActionPerformed
        // TODO add your handling code here:
        productname.setText("Navy Rum");
        productquantity.setText("1");
        productprice.setText("24");
    }//GEN-LAST:event_navyrumActionPerformed

    private void sweetciderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sweetciderActionPerformed
        // TODO add your handling code here:
        productname.setText("Sweet Cider");
        productquantity.setText("1");
        productprice.setText("18");
    }//GEN-LAST:event_sweetciderActionPerformed

    private void stoutbeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stoutbeerActionPerformed
        // TODO add your handling code here:
        productname.setText("Stout Beer");
        productquantity.setText("1");
        productprice.setText("18");
    }//GEN-LAST:event_stoutbeerActionPerformed

    private void scotchwhiskyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scotchwhiskyActionPerformed
        // TODO add your handling code here:
        productname.setText("Scotch Whisky");
        productquantity.setText("1");
        productprice.setText("39");
    }//GEN-LAST:event_scotchwhiskyActionPerformed

    private void bitterciderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bitterciderActionPerformed
        // TODO add your handling code here:
        productname.setText("Bitter Cider");
        productquantity.setText("1");
        productprice.setText("18");
    }//GEN-LAST:event_bitterciderActionPerformed

    private void rhumagricoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rhumagricoleActionPerformed
        // TODO add your handling code here:
        productname.setText("Rhum Agricole");
        productquantity.setText("1");
        productprice.setText("42");
    }//GEN-LAST:event_rhumagricoleActionPerformed

    private void totalpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalpriceActionPerformed

    private void calculateTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateTotalActionPerformed
        // TODO add your handling code here:
        String quantityString = productquantity.getText();
        String priceString = productprice.getText();

        int quantityInt = Integer.parseInt(quantityString);
        int priceInt = Integer.parseInt(priceString);
        int totalpriceInt = quantityInt * priceInt;
        String totalpriceString = String.valueOf(totalpriceInt);
        totalprice.setText(totalpriceString);
    }//GEN-LAST:event_calculateTotalActionPerformed

    private void addtoCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtoCartActionPerformed
        // TODO add your handling code here:
        if(productname.getText().equals("") || productquantity.getText().equals("") || productprice.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please Pick a Product!");
        }
        else if(totalprice.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Calculate the Total Price!");
        }
        else{
            int eachtotalprice = Integer.parseInt(totalprice.getText());
            overallprice += eachtotalprice;

            String getoverallprice = Integer.toString(overallprice);
            overallcost.setText(getoverallprice);

            String productpicked[] = {productname.getText(),productquantity.getText(),productprice.getText(),totalprice.getText()};

            DefaultTableModel cartlist = (DefaultTableModel)customercart.getModel();
            cartlist.addRow(productpicked);

            productname.setText("");
            productquantity.setText("");
            productprice.setText("");
            totalprice.setText("");
        }
    }//GEN-LAST:event_addtoCartActionPerformed

    private void customercartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customercartMouseClicked
        // This the customer cart list
        String productname = customercart.getValueAt(customercart.getSelectedRow(), 0).toString();
        String productquantity = customercart.getValueAt(customercart.getSelectedRow(), 1).toString();
        String productprice = customercart.getValueAt(customercart.getSelectedRow(), 2).toString();
        String producttotalprice = customercart.getValueAt(customercart.getSelectedRow(), 3).toString();
    }//GEN-LAST:event_customercartMouseClicked

    private void overallcostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overallcostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_overallcostActionPerformed

    private void comfirmcartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comfirmcartActionPerformed
        // Stores the User's Cart List
        ordernumber += 1;
        String orderID = Integer.toString(ordernumber);
        orderaddress.setText(orderID);
        String customeraddress = orderaddress.getText();
        String totaladdedcost = overallcost.getText();

        if(customercart.getRowCount() != 0){
            String thefilepath = "NetbeansProject\\Inventory Management and POS\\ F4 Data\\Customer Data\\"+customeraddress+".txt";
            File makefile = new File(thefilepath);
            try {
                FileWriter file = new FileWriter(makefile);
                BufferedWriter writethefile = new BufferedWriter(file);

                for(int r = 0; r < customercart.getRowCount(); r++){
                    for(int c = 0; c < customercart.getColumnCount(); c++){
                        writethefile.write(customercart.getValueAt(r, c).toString()+" ");
                    }
                    writethefile.newLine();
                }
                writethefile.close();
                file.close();

            } catch (IOException ex) {

            }
            overallcost.setText("");
            JOptionPane.showMessageDialog(this, "Your Cart has been Saved!\n Your Order Number is " +orderaddress.getText().toString());
        }
        else{
            JOptionPane.showMessageDialog(this, "No Data to be Saved");
        }
        
        

        cartlist.setRowCount(0);
    }//GEN-LAST:event_comfirmcartActionPerformed

    private void seethefileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seethefileActionPerformed
        // Presents the data within the file
        model.setRowCount(0);
        String address = enteredaddress.getText();

        String thefilepath = "NetbeansProject\\Inventory Management and POS\\ F4 Data\\Customer Data\\"+address+".txt";
        File getfile = new File(thefilepath);

        try {
            FileReader thefile = new FileReader(getfile);
            BufferedReader readingfile = new BufferedReader(thefile);

            DefaultTableModel listoforder = (DefaultTableModel)orderlist.getModel();
            Object[] eachline = readingfile.lines().toArray();

            for(int s = 0; s < eachline.length; s++){
                String[] perRow = eachline[s].toString().split(" ");
                listoforder.addRow(perRow);
            }
        } catch (FileNotFoundException ex) {
            
        }
    }//GEN-LAST:event_seethefileActionPerformed

    private void enteredaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enteredaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enteredaddressActionPerformed

    private void processOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processOrderActionPerformed
        // TODO add your handling code here:
        if (orderlist.getRowCount()!= 0){
            int prompt = JOptionPane.showOptionDialog(
                null, // Parent component (null for default)
                "Do you want to process the order?", // Message
                "Confirmation", // Title
                JOptionPane.YES_NO_OPTION, // Option type
                JOptionPane.QUESTION_MESSAGE, // Message type
                null, // Icon (null for default)
                new String[]{"Yes", "No"}, // Options
                "Yes" // Default option
                );
        if (prompt == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, "Order has been processed");
            model.setRowCount(0);
        }else{
            JOptionPane.showMessageDialog(this, "Order has been cancelled");
        }
        }else{
            JOptionPane.showMessageDialog(this, "Enter the order number first.");
        }
    }//GEN-LAST:event_processOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POSOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POSOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POSOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POSOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POSOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton addtoCart;
    private javax.swing.JButton bittercider;
    private javax.swing.JButton bourbonwhisky;
    private javax.swing.JButton cabernetsauvignonwine;
    private javax.swing.JToggleButton calculateTotal;
    private javax.swing.JButton chardonnaywine;
    private javax.swing.JButton comfirmcart;
    private javax.swing.JTable customercart;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton distilledsoju;
    private javax.swing.JTextField enteredaddress;
    private javax.swing.JButton fruitvodka;
    private javax.swing.JLabel fullNameLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton navyrum;
    private javax.swing.JButton oldtomgin;
    private javax.swing.JTextField orderaddress;
    private javax.swing.JTable orderlist;
    private javax.swing.JTextField overallcost;
    private javax.swing.JButton plainvodka;
    private javax.swing.JButton plymouthgin;
    private javax.swing.JButton processOrder;
    private javax.swing.JTextField productname;
    private javax.swing.JTextField productprice;
    private javax.swing.JTextField productquantity;
    private javax.swing.JButton rhumagricole;
    private javax.swing.JButton schwarzbier;
    private javax.swing.JButton scotchwhisky;
    private javax.swing.JButton seethefile;
    private javax.swing.JButton stoutbeer;
    private javax.swing.JButton sweetcider;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JTextField totalprice;
    // End of variables declaration//GEN-END:variables
}
